---
title: "DanishAgriculture1"
author: "Lasse Horsøe Østergaard & Gustav Lynggaard Vinther"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library & loading packages

```{r library}
library(tidyverse)
library(ggplot2)
```

# Loading Data

```{r}
DrivhusgasBrancher <- read_csv("data/CleanCsv/drivhusgas_udledning_branche_tid_clean.csv")
LandbrugRegnskab100 <- read_csv("data/CleanCsv/landbrug_regnskab_100_clean.csv")
LandbrugDrivhusgasser <- read_csv("data/CleanCsv/landbrug_udledning_drivhusgasser_clean.csv")
LandbrugbedrifterAreal <- read_csv("data/CleanCsv/landbrugbedrifter_dyrket_areal _1984-2022_clean.csv")
BruttoværditilvækstBrancher <- read_csv("data/CleanCsv/NABP10_bruttoværditilvækst_flere_brancher_clean.csv")
BeskæftigelseBrancher <- read_csv("data/CleanCsv/NKBB10_Beskæftigelse_brancher_1966-2022_clean.csv")
```

# Visualisation and analysis 

```{r}
head(LandbrugbedrifterAreal)
```


## Visualisation of area of Danish agriculture

```{r}
LandbrugbedrifterAreal %>% 
  ggplot(aes(x=år, y=samlet_dyrket_areal_ha))+
  geom_line()


```
```{r}
LandbrugbedrifterAreal %>% 
  ggplot(aes(x=år, y=dansk_landareal_2023_ha))+
  geom_line()
```






